# grafana/provisioning/datasources/datasource.yml
apiVersion: 1

datasources:
  - name: Elasticsearch
    type: elasticsearch
    access: proxy
    url: http://elasticsearch:9200
    database: weather_data
    jsonData:
      timeField: timestamp  # sampling time
      esVersion: 8
    isDefault: true
